name: dart_schema_parser
description: dart schema parser.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  recase: ^3.0.0
  dart_style: ^1.3.4
  inflection2: ^0.4.3

dev_dependencies:
  pedantic: ^1.8.0
